apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - ingress-patch.yaml

images:
  - name: wolfix1245/userwebsite
    newTag: "2ef25c15ab94d63f0a8b6d582712fa44c59024a8"

commonLabels:
  environment: staging