apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - ingress-patch.yaml

images:
  - name: wolfix1245/complex
    newTag: "1803198cd7f9c79d9f35262087ca41e746c995a2"

commonLabels:
  environment: staging