apiVersion: v1
kind: Service
metadata:
  name: complex
  labels:
    app: complex
spec:
  type: ClusterIP
  selector:
    app: complex
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP