apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landingcomplex-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mamad.wolfixsite.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landingcomplex-service
                port:
                  number: 80