apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - ingress-patch.yaml

images:
  - name: wolfix1245/userwebsite
    newTag: "dev-latest"

commonLabels:
  environment: development