apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landingcomplex-ingress
spec:
  tls:
  - hosts:
    - staging.wolfixor.shop
    secretName: landing-staging-tls
  rules:
  - host: staging.wolfixor.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landingcomplex-app
            port:
              number: 80