apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: complex-ingress
spec:
  tls:
  - hosts:
    - complexdev.wolfixor.shop
    secretName: complex-dev-tls
  rules:
  - host: complexdev.wolfixor.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: complex
            port:
              number: 80